
import Link from 'next/link';

export default function TermsOfUse() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 sm:p-8 md:p-12">
      <div className="z-10 w-full max-w-4xl">
        <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-center mb-8">
          Terms of Use
        </h1>
        <p className="text-center text-muted-foreground mb-12">Last Updated: JAN 21, 2026</p>

        <div className="space-y-8 text-left text-foreground/80">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">1. Acceptance of Terms</h2>
            <p>By using EndItForMe ("the Service"), you agree to these Terms of Use. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">2. Description of Service</h2>
            <p className="mb-2">EndItForMe is an entertainment and satirical service that generates AI-scripted text messages for breakups based on user inputs. The Service offers two distinct personas:</p>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>"Toxic Chaos"</strong> – Dramatized, messy, and emotional scripts.</li>
              <li><strong>"Corporate HR"</strong> – Satirical parody scripts that frame relationships as employment contracts.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">3. Age Requirement</h2>
            <p>You must be at least 18 years old to use this Service. The content generated involves adult relationship themes.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">4. Pricing and Payment</h2>
             <ul className="list-disc list-inside space-y-1">
                <li>Each generated message costs $1.00 USD.</li>
                <li>Payment is processed immediately through Stripe.</li>
                <li>All sales are final – NO REFUNDS.</li>
                <li>You receive one AI-generated text draft per payment.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">5. No Professional or Legal Advice</h2>
            <p className="font-bold mb-2">IMPORTANT DISCLAIMER: The Service provides ENTERTAINMENT AND PARODY CONTENT ONLY. Our AI-generated responses are NOT:</p>
            <ul className="list-disc list-inside space-y-1 mb-4">
                <li>Professional relationship counseling.</li>
                <li>Legal advice (specifically regarding termination of contracts or employment).</li>
                <li>Psychological or medical advice.</li>
            </ul>
            <p className="font-semibold">HR Mode Specific Disclaimer: The "Corporate HR" persona is a fictional, satirical format. It does not constitute a valid legal termination of employment, housing, or financial contracts. Do not use this service for actual employment terminations.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">6. AI-Generated Content</h2>
            <p className="mb-2">All responses are generated by artificial intelligence (Google AI Gemini). The AI:</p>
            <ul className="list-disc list-inside space-y-1">
                <li>May generate content that is factually irrelevant to your specific situation.</li>
                <li>May generate biased or overly aggressive content based on the "Toxic" persona.</li>
                <li>Does not know the specific individuals involved in your relationship.</li>
            </ul>
            <p className="mt-4">You use the AI responses at your own risk. You are solely responsible for the decision to send the generated text.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">7. Acceptable Use (Strictly Enforced)</h2>
            <p className="mb-2">You agree NOT to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1">
                <li>Harass, threaten, or stalk any individual.</li>
                <li>Violate any restraining orders or domestic violence protection orders.</li>
                <li>Impersonate real legal entities or actual companies using the "HR Mode."</li>
                <li>Generate hate speech or threats of physical violence.</li>
                <li>Use the Service for illegal purposes.</li>
                <li>Reverse-engineer, scrape, or automate queries to the Service.</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">8. Content Ownership & License</h2>
            <p className="mb-2"><strong>Your Input:</strong> You own the specific details (reasons) you submit.</p>
            <p className="mb-2"><strong>Our Service:</strong> We own the website code, branding, and the specific "Prompt Engineering" logic used to generate the texts.</p>
            <p><strong>The Output:</strong> We grant you a non-exclusive, perpetual license to use the generated text for your personal communication (i.e., sending the breakup text).</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">9. Intellectual Property</h2>
            <p>"EndItForMe," the "Toxic/HR" persona concepts, logos, and website design are our intellectual property. Unauthorized commercial reproduction is prohibited.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">10. No Warranties</h2>
            <p>The Service is provided "AS IS" without warranties of any kind. We do not guarantee that the generated text will successfully end your relationship or result in a specific emotional outcome.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">11. Limitation of Liability</h2>
            <p className="mb-2">TO THE MAXIMUM EXTENT PERMITTED BY LAW: We are NOT liable for:</p>
            <ul className="list-disc list-inside space-y-1">
                <li>The reactions of the recipient of your message.</li>
                <li>Emotional distress arising from the use of the Service.</li>
                <li>Any damages arising from the use of the Service.</li>
                <li>Third-party actions (including Stripe or Google).</li>
            </ul>
            <p className="mt-4">Your maximum recovery is limited to the amount you paid ($1.00).</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">12. Indemnification</h2>
            <p>You agree to indemnify and hold us harmless from any claims, damages, lawsuits, or expenses (including legal fees) arising from:</p>
             <ul className="list-disc list-inside space-y-1">
                <li>Your sending of the generated message.</li>
                <li>Your violation of these Terms.</li>
                <li>Your violation of any law (including harassment laws) or third-party rights.</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">13. No Refund Policy</h2>
            <p className="mb-2">ALL SALES ARE FINAL. Because you receive instant digital delivery of the AI-generated content (the text draft), we do not offer refunds for any reason, including:</p>
             <ul className="list-disc list-inside space-y-1">
                <li>Dissatisfaction with the "tone" of the breakup.</li>
                <li>Reconciliation with your partner.</li>
                <li>Change of mind.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">14. Service Modifications</h2>
             <ul className="list-disc list-inside space-y-1">
                <li>Modify or discontinue the Service at any time.</li>
                <li>Refuse service to anyone for any reason (specifically for violation of Acceptable Use).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">15. Termination</h2>
            <p>We may terminate your access immediately if you violate these Terms or engage in abusive behavior toward the AI system.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">16. Third-Party Services</h2>
            <p className="mb-2">Our Service uses:</p>
            <ul className="list-disc list-inside space-y-1">
                <li>Stripe for payment processing.</li>
                <li>Google AI for processing.</li>
                <li>Vercel/Firebase for hosting. We are not responsible for outages or data handling by these third parties.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">17. Governing Law</h2>
            <p>These Terms are governed by the laws of [Your State/Country], without regard to conflict of law principles.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">18. Dispute Resolution</h2>
            <p><strong>Arbitration Agreement:</strong> Any disputes will be resolved through binding arbitration rather than court. You waive the right to a jury trial or class action.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">19. Severability</h2>
            <p>If any provision is found unenforceable, the remaining provisions remain in effect.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">20. Entire Agreement</h2>
            <p>These Terms constitute the entire agreement between you and EndItForMe regarding the Service.</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">21. Contact Information</h2>
            <p>For questions about these Terms: Email: <a href="mailto:answers@enditforme.com" className="text-primary hover:underline">answers@enditforme.com</a> Website: enditforme.com</p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold mb-4 text-foreground">22. Acknowledgment</h2>
            <p>By clicking "Pay & Generate" or using the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use and our Privacy Policy.</p>
          </section>

        </div>
        <div className="text-center mt-12">
            <Link href="/" className="text-primary hover:underline">
                &larr; Back to Home
            </Link>
        </div>
      </div>
    </main>
  );
}
